// Code generated by MockGen. DO NOT EDIT.
// Source: dao/service.go

package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockService is a mock of Service interface
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CompanyHasAuthCode mocks base method
func (m *MockService) CompanyHasAuthCode(companyNumber string) (bool, error) {
	ret := m.ctrl.Call(m, "CompanyHasAuthCode", companyNumber)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompanyHasAuthCode indicates an expected call of CompanyHasAuthCode
func (mr *MockServiceMockRecorder) CompanyHasAuthCode(companyNumber interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompanyHasAuthCode", reflect.TypeOf((*MockService)(nil).CompanyHasAuthCode), companyNumber)
}
